config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasklists#index'

  resources :tasklists do

    resources :tasks

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :name, presence: true

    belongs_to :tasklist
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
    validates :name, presence: true

    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/tasks_controller.rb
class TasksController < ApplicationController

  def create
    tasklist = Tasklist.find(params[:tasklist_id])

    task_params = params[:task].permit(:name, :description, :duedate, :priority, :status)

    task = tasklist.tasks.new(task_params)

    task.save

    redirect_to tasklist_path(id: tasklist.id)

    # if task.save
    #     redirect_to tasklist_path(id: tasklist.id)
    # else
    #     if task.name == ""
    #        flash[:notice] = "Please enter a valid name for the task!"
    #     end
    #     redirect_to new_tasklist_task_path
    # end
  end

  def edit
    @task = Task.find(params[:id])

  end

  def update
    # tasklist_params = params[:tasklist].permit(:name, :description, :duedate, :status)
    # @tasklist = Tasklist.find(params[:id])

    # if @tasklist.update(tasklist_params)
    #     redirect_to tasklist_path(id: @tasklist.id)
    # else
    #      if @tasklist.name == ""
    #        flash[:notice] = "Please enter a valid name for the tasklist!"
    #      end
    #     render :edit
    # end
  end

  def destroy
    @task = Tasks.find(params[:id])
    flash[:notice] = "Task '#{@task.name}' successfully deleted"
    tasklist_id = @task.tasklist_id
    @task.destroy
    redirect_to tasklist_path(id: tasklist_id)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController

  def index
    @tasklists = Tasklist.all
  end

  def show
    @tasklist = Tasklist.find(params[:id])
    @task = @tasklist.tasks.build
  end

  def new
    @tasklist = Tasklist.new
  end

  def create
    tasklist_params = params[:tasklist].permit(:name, :description, :duedate, :status)

    tasklist = Tasklist.new(tasklist_params)

    if tasklist.save
        redirect_to tasklist_path(id: tasklist.id)
    else
        if tasklist.name == ""
           flash[:notice] = "Please enter a valid name for the tasklist!"
        end
        redirect_to new_tasklist_path
    end
  end

  def edit
    @tasklist = Tasklist.find(params[:id])
  end

  def update
    tasklist_params = params[:tasklist].permit(:name, :description, :duedate, :status)
    @tasklist = Tasklist.find(params[:id])

    if @tasklist.update(tasklist_params)
        redirect_to tasklist_path(id: @tasklist.id)
    else
         if @tasklist.name == ""
           flash[:notice] = "Please enter a valid name for the tasklist!"
         end
        render :edit
    end
  end

  def destroy
    @tasklist = Tasklist.find(params[:id])
    flash[:notice] = "Tasklist '#{@tasklist.name}' successfully deleted"
    @tasklist.destroy
    redirect_to tasklists_path

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  </head>

  <body class="<% controller_name %> <%= action_name %>">
    <div id="container">

    <div > <% flash.class %> </div>
    <div class="notice">
      <%- flash.each do |key,value| %>
        <% key %>
        <div class="alert alert-danger"><%= value %></div>
      <% end %>
    </div>
    <div> <% flash %>  </div>
         <%= yield %>
    </div>
  </body>

</html>

app/views/tasklists/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
       <h1>Edit Tasklist</h1>
       
       <%= form_for @tasklist, url: tasklist_path(id: @tasklist.id), method: :put do |f| %>

      <div class="form-group">
        <%= f.label   :name , class: "control-label col-sm-2"%>
        <div class="col-sm-8 col-sm-offset-2"><%= f.text_field :name , class: "form-control"  %></div>
      </div>
      <div class="form-group">
        <%= f.label :description , class: "control-label col-sm-2" %>
       <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :description , class: "form-control "  %></div>
      </div>
      <div class="form-group">
        <%= f.label :duedate , class: "control-label col-sm-2" %>
       <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :duedate , class: "form-control" %></div>
      </div>

      <%= f.hidden_field :status, :value => "In progress" %>


      <div id="newButtons">

      <%= link_to 'Back to Tasklist', tasklist_path(id: @tasklist.id), class: "btn btn-primary pull-left" %>  

      <%= f.submit "Update" , class: "btn btn-success pull-right" %>
        
      </div>

      <% end %>

      
  </div>
</div>

  <script>

        var form = document.getElementById("new_tasklist");
        form.className += " form-horizontal";
        console.log(form.className);
      
  </script>

app/views/tasklists/index.html.erb
<div class="row">
    <div id="dashHead" class="col-md-4 col-md-offset-4">
      <h1>To Do App Dashboard!</h1>
    </div>
</div>
<div class="row">
  <div id="dashBody" class="col-md-4 col-md-offset-4">
  <h2>Outstanding Tasklists (<%= @tasklists.count %>)</h2> <!-- display tasks due in next 1 week -->
  <!-- option to change filter/remove view -->

  <table class="table table-striped">
  
    <thead>
      <th>List Name</th>
      <th>Due Date</th>
      <th>Description</th>
      <th>View</th>
    </thead>
  
  <tbody>
  
  <% @tasklists.each do |tasklist| %>
    <tr>
      <td>
        <%= tasklist.name %>
      </td>
      <td>
        
        <%= tasklist.duedate.to_date %>
        
      </td>
      <td>
        <%= tasklist.description%>
      </td>
      <td >
        <%= link_to 'View', tasklist_path(id: tasklist.id), class:"btn btn-success" %>
      </td>
    </tr>

  <% end %>

  </tbody>

</table>
  
   <%= link_to 'Create New Tasklist', new_tasklist_path, class: "btn btn-primary btn-lg " %>

  </div>
</div>


<div class="row">
   <div id="archived" class="col-md-4 col-md-offset-4"> 
      <h2>Archived Tasklists</h2>
      <!-- TODO link to completed/archived tasklists --> 
  </div>
</div>

app/views/tasklists/new.html.erb
 
<div class="row">
  <div class="col-md-4 col-md-offset-4">
       <h1>Create new Tasklist</h1>
       
       <%= form_for @tasklist, url:tasklists_path, method: :post do |f| %>

      <div class="form-group">
        <%= f.label   :name , class: "control-label col-sm-2"%>
        <div class="col-sm-8 col-sm-offset-2"><%= f.text_field :name , class: "form-control"  %></div>
      </div>
      <div class="form-group">
        <%= f.label :description , class: "control-label col-sm-2" %>
       <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :description , class: "form-control "  %></div>
      </div>
      <div class="form-group">
        <%= f.label :duedate , class: "control-label col-sm-2" %>
       <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :duedate , class: "form-control" %></div>
      </div>

      <%= f.hidden_field :status, :value => "In progress" %>


      <div id="newButtons">

      <%= link_to 'Back to Index', tasklists_path, class: "btn btn-primary pull-left" %>  

      <%= f.submit "Create" , class: "btn btn-success pull-right" %>
        
      </div>

      <% end %>

      
  </div>
</div>

  <script>

        var form = document.getElementById("new_tasklist");
        form.className += " form-horizontal";
        console.log(form.className);
      
  </script>

app/views/tasklists/show.html.erb
<div class="row">

      <h1> Tasklist Details </h1>

      <div id="showContent" class="col-md-6 col-md-offset-1 pull-left">

      
        <div id="showTitle">
            <div><h2 id="showName"> <%= @tasklist.name %> </h2> <span id="showDuedate">Due by: <%= @tasklist.duedate.to_date %></span> <span id="editBtn"><%= link_to 'Edit', edit_tasklist_path, class:"btn btn-default" %></span><span id="deleteBtn"><%= link_to 'Delete Tasklist', tasklist_path(id: @tasklist.id),method: :delete, class:"btn btn-danger" %></span></div> 

          <p id="showDescription"> by <%= @tasklist.description %></p> 


            <div id="displayTasks">
              <!-- <h3>Tasks:</h3> -->
              
                  <% if (@tasklist.tasks.empty?) == false %>
                    <% @tasklist.tasks.each do |task| %>
                    <% if task.valid? %>
                      <div class="panel panel-primary">
                        <div class="panel-heading">
                          <h4 class="panel-title"> <%= task.name %> <span class="taskDate"> <%= task.duedate %></span> </h4> 
                        </div>
                          <p class="panel-body"> <%= task.description %> </p>

                      
                      </div>
                      <% end %>
                    <% end %>
                   <% else %>
                    <p> No Tasks in this tasklist yet. </p>
                  <% end %>
                 <!-- <i class='fa fa-pencil-square-o fa-2x pull-right' aria-hidden='true'></i>  -->
              
            </div>

      <div id="newTask" >

          <h1>Create new Task</h1>
       
       <%= form_for @task, url: tasklist_tasks_path(tasklist_id: @tasklist.id), method: :post do |f| %>

      <div class="form-group">
          <%= f.label   :name , class: "control-label col-sm-2"%>
          <div class="col-sm-8 col-sm-offset-1"><%= f.text_field :name , class: "form-control"  %></div>
      </div>
      <div class="form-group">
          <%= f.label :description , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-1"> <%= f.text_field :description , class: "form-control "  %></div>
      </div>
      <div class="form-group">
          <%= f.label :duedate , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-1"> <%= f.text_field :duedate , class: "form-control" %></div>
       </div>
       <div class="form-group">
          <%= f.label :priority , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-1"> <%= f.text_field :priority , class: "form-control" %></div>
      </div>

      <%= f.hidden_field :status, :value => "In progress" %>

      

      <%= f.submit "Create Task" , class: "btn btn-success pull-right" %>

      <% end %>

        </div>
      
        


        </div>

        

    </div>

</div>

<div class="row">

  <div class="col-md-6 col-md-offset-1">

  <div id="showButtons" class="pull-left">

           

           

           <%= link_to 'Back to Index', tasklists_path, class:"btn btn-primary" %>
             
        </div>

  </div>
</div>

app/views/tasks/edit.html.erb
 
<div class="row">
  <div class="col-md-4 col-md-offset-4">
       <h1>Edit Task</h1>
       
       <%= form_for @task, url: tasklist_tasks_path(tasklist_id: @task.tasklist_id), method: :put do |f| %>

      <div class="form-group">
          <%= f.label   :name , class: "control-label col-sm-2"%>
          <div class="col-sm-8 col-sm-offset-2"><%= f.text_field :name , class: "form-control"  %></div>
      </div>
      <div class="form-group">
          <%= f.label :description , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :description , class: "form-control "  %></div>
      </div>
      <div class="form-group">
          <%= f.label :duedate , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :duedate , class: "form-control" %></div>
       </div>
       <div class="form-group">
          <%= f.label :priority , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :priority , class: "form-control" %></div>
      </div>

      <%= f.hidden_field :status, :value => "In progress" %>


      <div id="newButtons">

      <%= link_to 'Back to tasklist', tasklist_path(id: @task.tasklist_id), class: "btn btn-primary pull-left" %>  

      <%= f.submit "Update Task" , class: "btn btn-success pull-right" %>
        
      </div>

      <% end %>

      
  </div>
</div>

  <script>

        var form = document.getElementById("new_task");
        form.className += " form-horizontal";
        console.log(form.className);
      
  </script>

app/views/tasks/new.html.erb
 
<div class="row">
  <div class="col-md-4 col-md-offset-4">
       <h1>Create new Task</h1>
       
       <%= form_for @task, url: tasklist_tasks_path(tasklist_id: @task.tasklist_id), method: :post do |f| %>

      <div class="form-group">
          <%= f.label   :name , class: "control-label col-sm-2"%>
          <div class="col-sm-8 col-sm-offset-2"><%= f.text_field :name , class: "form-control"  %></div>
      </div>
      <div class="form-group">
          <%= f.label :description , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :description , class: "form-control "  %></div>
      </div>
      <div class="form-group">
          <%= f.label :duedate , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :duedate , class: "form-control" %></div>
       </div>
       <div class="form-group">
          <%= f.label :priority , class: "control-label col-sm-2" %>
         <div class="col-sm-8 col-sm-offset-2"> <%= f.text_field :priority , class: "form-control" %></div>
      </div>

      <%= f.hidden_field :status, :value => "In progress" %>


      <div id="newButtons">

      <%= link_to 'Back to tasklist', tasklist_path(id: @task.tasklist_id), class: "btn btn-primary pull-left" %>  

      <%= f.submit "Create Task" , class: "btn btn-success pull-right" %>
        
      </div>

      <% end %>

      
  </div>
</div>

  <script>

        var form = document.getElementById("new_task");
        form.className += " form-horizontal";
        console.log(form.className);
      
  </script>